Repository kambiz-frounchi/WheelsGoneWild, pull requests merged in 2020-08, with the labels that each got.

#2 somehow missed travis/lint files
  .eslintignore
  .eslintrc.json
  .travis.yml
Labels: documentation

#19 Bike price
  Data.xlsx
  models/bike.js
Labels: documentation, enhancement

#22 Bike price show
  public/images/background.svg
  public/js/index.js
  public/stylesheets/index.css
  views/index.handlebars
  views/layouts/main.handlebars
Labels: enhancement

#27 Shopping cart api
  Data.xlsx
  config/middleware/isAuthenticated.js
  public/js/index.js
  public/js/login.js
  public/js/signup.js
  public/login.html
  public/signup.html
  routes/api-routes.js
  routes/html-routes.js
  server.js
  views/index.handlebars
  views/layouts/main.handlebars
Labels: enhancement

#32 Shopping cart api
  config/middleware/isAuthenticated.js
  models/order.js
  models/orderItem.js
  models/user.js
  public/images/background.svg
  public/js/index.js
  public/stylesheets/index.css
  routes/api-routes.js
  routes/html-routes.js
  views/index.handlebars
  views/layouts/main.handlebars
  views/partials/bikelist.handlebars
  views/partials/filter.handlebars
  views/partials/guestmenu.handlebars
  views/partials/jumbotron.handlebars
  views/partials/shoppingcart.handlebars
  views/partials/usermenu.handlebars
  views/profile.handlebars
Labels: enhancement

#41 runtime fixes
  models/order.js
  models/user.js
Labels: bug
